apiVersion: apps/v1
kind: Deployment
metadata:
  name: psico-clinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psico-clinic-app
  template:
    metadata:
      labels:
        app: psico-clinic-app
    spec:
      containers:
      - name: psico-clinic-app
        image: psico_clinic_app:0.5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: psico-clinic-service
spec:
  type: NodePort
  selector:
    app: psico-clinic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
